<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
    $page = "download";
    $language = "en";
    include_once "head.php";
    ?>
    <title>Magellan Download</title>
</head>
<body>
    <div id="container">
      <?php
    include_once "functions.php";
    include_once "navi_" . $language . ".php";
    include_once "header.php";
    ?>
      <div id="center">
            <h2>Download</h2>
            <p>On this page you can find all available downloads for Magellan. Except for Magellan
                1.x, all JAR files are executable. Magellan 2.x, and the plugins are divided into
                multiple files that can be installed in any directory (for example also on a USB
                stick).</p>
            <h2>Installation</h2>
            <p>
                From version 2.1.0 (build 752) on, after downloading the installer for your
                operating system, simply run the executable file
                <code>Magellan_installer...</code>
            </p>
            <p>
                The installer will install all necessary files and, if you want, links on your
                desktop and the start menu. To execute Magellan, simply use this link or run the
                file magellan_launcher in the magellan directory You may edit the file
                <code>magellan_launcher.vmoptions</code>
                if you have special needs, for example with regards to memory. Usually this isn't
                necessary.
            </p>
            <p>
                Up to and including version 2.0.9 you have to install <a href="index_de.php#java">Java</a>
                first, then run the Magellan installer by simply double clicking the file
                magellan_vX.Y.Z.jar or running the command
                <code>java -jar magellan_vX.Y.Z</code>
                . You would then run the Magellan itself by using the links or starting magellan.bat
                or magellan.sh.
            </p>
            <p>
                A Java version is installed by the installer if necessary. You can find more
                information on Java on the <a href="index_de.php#java">main page</a>.
            </p>
            <p>
                <!-- Link required in exchange for open source license for install4j! -->
                Our installer has been generated by the multi platform installer builder <a
                    href=https://www.ej-technologies.com/products/install4j/overview.html>install4j</a>.
            </p>
            <a name="magellan2"></a>
            <h3>Download Magellan 2.x</h3>
            <p>
                Here you can find the current stable release of Magellan2.x. 
                This version is recommended for all users and
                mostly stable. In the
                <?php
                if (empty($RELEASE['changelog']))
                    echo "CHANGELOG";
                else
                    echo "<a href=\"{$RELEASE['changelog']}\">CHANGELOG</a>";
                ?>
                you can find all the changes since the last release.
            </p>
            <?php
            if (empty($RELEASE))
                echo "<p><strong>Fehler:</strong> Release nicht gefunden bei 
                          <a href='https://github.com/magellan2/magellan2/releases' class='externalLink'>GitHub</a>!</p>";
            ?>
            <p>
           Version: <?php echo $RELEASE['version']['raw']; ?><br />
           Status: <?php echo $RELEASE['formatted_time']; ?><br />
            </p>
            <ul>
            <?php
            download_link($RELEASE['jar'], "JAR installer (Windows, Linux)");
            download_link($RELEASE['windows-x64'], "Windows");
            download_link($RELEASE['unix'], "Linux");
            download_link($RELEASE['macos'], "MacOS");
            download_link($RELEASE['zip'], "ZIP file");
            download_link($RELEASE['url'], "Source code at github (for developers)", true);
            ?>
            </ul>
            <br /> <a name="NightlyBuild" id="NightlyBuild"></a>
            <h3>Nightly Build</h3>
            <p>
                Here you can find the latest version of Magellan 2.x.
                This version is compiled whenever we make changes, and it may be
                unstable. So it is recommended for developers and beta
                testers only. In the 
                <?php
                if (empty($LATEST['changelog']))
                    echo "CHANGELOG";
                else
                    echo "<a href=\"{$LATEST['changelog']}\">CHANGELOG</a>";
                ?>
                you can find all changes made since the last build.
            </p>
            <p>
           Version: <?php echo $LATEST['version']['raw']; ?><br />
           Status: <?php echo $LATEST['formatted_time']; ?><br />
            </p>
            <ul>
            <?php
            download_link($LATEST['jar'], "JAR installer (Windows, Linux)");
            download_link($LATEST['windows-x64'], "Windows");
            download_link($LATEST['unix'], "Linux");
            download_link($LATEST['macos'], "MacOS");
            download_link($LATEST['zip'], "ZIP file");
            download_link("https://github.com/magellan2/magellan2/releases", "All Releases at github (for developers)", true);
            ?>
            </ul>
            <br /> <a name="magellan1"></a>
            <h3>Download Magellan 1.x</h3>
            <p>The development of the old Magellan client has stopped because of the huge amount of
                changes in the new release. It's not possible to transfer every necessary patch to
                this version. The latest version is 1.2.5h.</p>
            <p>
                You can download the latest version at <a class="externalLink"
                    href="https://sourceforge.net/project/showfiles.php?group_id=174030/">SourceForge</a>.
            </p>
            <br /> <a name="plugins"></a>
            <h3>Download Plugins</h3>
            <p>
                Here you can find some plugins that are available directly from this server.
                Additional versions might be available <a
                    href="https://github.com/magellan2/magellan2-extensions-plugins/releases">on
                    GitHub</a>
            </p>
            <ul>
                <li><b>MapCleaner Plugin</b><br /> Repairs Reports<br /> see <a
                    href="plugins_mapcleaner_en.php">Description</a><br /> Download for 2.0.5: <a
                    href="plugins/mapcleaner-installer-for2.0.5.jar">Installer JAR</a><br />
                    Download for nightly: <?php latest_plugin_release_link('mapcleaner', 'Installer JAR', true); ?><br />
                    <br /></li>
                <li><b>MemoryWatch Plugin</b><br /> Shows Magellan memory usage<br /> see <a
                    href="plugins_memorywatch_en.php">Description</a><br /> Download for 2.0.5: <a
                    href="plugins/memorywatch-installer-for2.0.5.jar">Installer JAR</a><br />
                    Download for nightly: <?php latest_plugin_release_link('memorywatch', 'Installer JAR', true); ?><br />
                    <br /></li>
                <li><b>Statistics Plugin</b><br /> Shows graphs and tables for historic data of a
                    report<br /> see <a href="plugins_statistics_en.php">Description</a><br />
                    Download for nightly: <?php latest_plugin_release_link('statistics', 'Installer JAR', true); ?><br />
                    <br /></li>
                <li><a name="teacher"></a> <b>Teacher Plugin</b><br /> Simplifies teacher learner
                    relations.<br /> see <a href="plugins_teacher_en.php">Description</a><br />
                    Download for 2.0.5: <a href="plugins/teacher-installer-for2.0.5.jar">Installer
                        JAR</a> Version 0.10.4<br /> Download for nightly: <?php latest_plugin_release_link('teacher', 'Installer JAR', true); ?><br />
                    <br /></li>
                <li><a name="shiploader"></a> <b>ShipLoader Plugin</b><br /> Load your ships with
                    ease...<br /> see <a href="plugins/README.shiploader.txt">Description</a><br />
                    Download for 2.0.5: <a href="plugins/shiploader-installer-for2.0.5.jar">Installer
                        JAR</a> Version 0.1.1<br /> Download for nightly: <?php latest_plugin_release_link('shiploader', 'Installer JAR', true); ?><br />
                    <br /></li>
                <li><a name="mapicons"></a> <b>MapIcons Plugin</b><br /> Important messages seen on
                    the map<br /> see <a href="plugins_mapicons_en.php">Description</a><br />
                    Download (Magellan 2.0.5): <a href="plugins/mapicons-installer_2_0_5.jar">Installer
                        JAR</a> Version 0.96<br /> Download for nightly: <?php latest_plugin_release_link('mapicons', 'Installer JAR', true); ?><br />
                    <br /></li>

                <li><a name="lighthouseicons"></a> <b>LightHouseIcons Plugin</b><br /> Current by
                    lighthouse controlled regions and the maximum range of all lighthouse are
                    visible<br /> see <a href="plugins_lighthouseicons_en.php">Description</a><br />
                    Download (all versions): <?php latest_plugin_release_link('lighthouseicons', 'Installer JAR', true); ?><br />
                    <br /></li>
            </ul>

            <a name="tools"></a>
            <h3>Download Tools</h3>
            <p>Next is our tools-section. For now, these tools are available for download:</p>
            <ul>
                <li><b>Console Merger</b><br /> Merges two reports. needs an Magellan2 installation,
                    but no running Magellan2 application.<br /> see <a
                    href="tools_consolemerger_en.php">Description</a><br /> Download (for Magellan
                    2.0.5): <a href="tools/consolemerger-for2.0.5.jar">executable JAR</a><br />
                    Download (for Magellan "nightly): <a href="tools/consolemerger.jar">executable
                        JAR</a><br /> <br /></li>
            </ul>
        </div>
    </div>
</body>
</html>
